name: '52签到'

on:
  schedule:
    - cron: '30 16 * * *'
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2
     - name: 'setup python'
       uses: actions/setup-python@master
       with: 
         python-version: 3.7
       
     - name: main
       env:
         SCKEY: ${{ secrets.SCKEY }}
         cookie_52pj: ${{ secrets.cookie_52pj }}
       run: |
         pip3 install -r requirement.txt
         python3 ./Checkin52pj/Checkin52pjForSCF.py
